version: '3'
services:
  meaw_pong:
    image: nginx:latest
    container_name: meaw_pong
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8000:80
    restart: always

  user_management:
    container_name: "user_management"
    build: ./backend
    ports: 
      - "9000:9000"